FROM arm32v7/ubuntu:latest

MAINTAINER cade <cade.call@mediciventures.com>

EXPOSE $RPCPORT

EXPOSE $PORT

RUN useradd -ms /bin/bash esa

RUN mkdir /etc/esa

RUN mkdir /var/lib/esa

RUN chown esa:esa /etc/esa /var/lib/esa

WORKDIR /home/esa

COPY --chown=esa:esa linux64/* ./run.sh /home/esa/

USER esa

CMD ["/home/esa/run.sh"]
